version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase: printing versions"
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Pre-build: installing dependencies"
      - npm install

  build:
    commands:
      - echo "Build started on `date`"
      - npm run build || echo "No build step, just starting app check"

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
